### ISSUE TITLE
mach-core zig version

### ISSUE THREAD

**Issue by g-tejas** [mitchellh/zig-overlay#35]
Is it possible to get the nix shell to work with a specific nightly build, specifically the one mentioned here "https://machengine.org/about/zig-version/"? I dont think this is the latest nightly build, so its a few weeks old, and using zigpkgs."0.12.0" doesnt work

**Comment by mitchellh** [comment]
You can use any version in [sources.json](https://github.com/mitchellh/zig-overlay/blob/main/sources.json). The README covers the format, its `packages.<version>` where version is the key in that JSON file.

**Comment by g-tejas** [comment]
Ahh, but it seems to be missing the nightly that mach-core supports, is there a way i can manually add it?

**Comment by mitchellh** [comment]
You can fork the repo, but the way the json is today it only supports one build per day. Our CI runs every 6 hours and so whatever it finds latest -- for that calendar day -- it uses.
